# Generated by Django 3.2.11 on 2022-02-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='models:registration_title_help_text', max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('applicants', models.ManyToManyField(default=None, related_name='applicant_for', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='registrations_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
