# Generated by Django 3.2.11 on 2022-02-14 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='applicants',
            field=models.ManyToManyField(default=None, related_name='applicant_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='registrations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
