# Generated by Django 3.2.12 on 2022-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20220221_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uses_information',
            field=models.BooleanField(blank=True, choices=[(False, 'models:registration:registration_uses_information_false'), (True, 'models:registration:registration_uses_information_true')], null=True),
        ),
    ]
