# Generated by Django 3.2.11 on 2022-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20220217_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('has_consented', models.BooleanField(default=False)),
            ],
        ),
    ]
