# Generated by Django 3.2.14 on 2022-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_confirm_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='involves_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='involves_guardian_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='involves_non_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='involves_other_people',
            field=models.BooleanField(default=False),
        ),
    ]
