# Generated by Django 3.2.14 on 2022-07-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20220725_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='consent_document_storage',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('non_applicable', 'models:choices:non_applicable')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='registration',
            name='data_storage',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='registration',
            name='multimedia_storage',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('non_applicable', 'models:choices:non_applicable')], default='', max_length=25),
        ),
        migrations.CreateModel(
            name='Involved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consent', 'models:involved:consent'), ('non_consent', 'models:involved:non_consent'), ('guardian_consent', 'models:involved:guardian'), ('other', 'models:involved:other')], max_length=25)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_groups', to='registrations.registration')),
            ],
        ),
    ]
