# Generated by Django 3.2.14 on 2022-08-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20220728_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='involved',
            old_name='type',
            new_name='group_type',
        ),
    ]
