# Generated by Django 3.2.16 on 2023-01-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20230126_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='third_party_sharing',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='audio_video_kept_details',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
