# Generated by Django 3.2.16 on 2023-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_auto_20230126_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='audio_video_kept',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('n_a', 'models:choices:non_applicable'), ('', 'models:choices:please_specify')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='consent_document_storage',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('n_a', 'models:choices:non_applicable'), ('', 'models:choices:please_specify')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='data_storage',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('', 'models:choices:please_specify')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ic_storage_decade',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('', 'models:choices:please_specify')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='multimedia_storage',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('n_a', 'models:choices:non_applicable'), ('', 'models:choices:please_specify')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='registration',
            name='raw_data_decade',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('', 'models:choices:please_specify')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='third_party_sharing',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('', 'models:choices:please_specify')], default='', max_length=25),
        ),
    ]
