# Generated by Django 3.2.16 on 2023-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_auto_20230210_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uses_software',
            field=models.CharField(choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('', 'models:choices:please_specify')], default='', max_length=10),
        ),
    ]
