# Generated by Django 3.2.16 on 2023-02-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_registration_uses_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrations.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='registrations.registration'),
            preserve_default=False,
        ),
    ]
