# Generated by Django 3.2.16 on 2023-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_auto_20230210_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='not_approved',
            field=models.CharField(blank=True, choices=[('yes', 'models:choices:yes'), ('no', 'models:choices:no'), ('', 'models:choices:please_specify')], max_length=10, null=True),
        ),
    ]
