# Generated by Django 3.2.16 on 2023-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_auto_20230308_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500, verbose_name='models:faq:verbose_name:title')),
                ('answer', models.TextField(default='', max_length=5000, verbose_name='models:faq:verbose_name:answer')),
                ('front_page', models.BooleanField(default=False, verbose_name='models:faq:verbose_name:front_page')),
                ('external_url', models.CharField(blank=True, default='', max_length=500, verbose_name='models:faq:verbose_name:external_url')),
                ('external_url_text', models.CharField(blank=True, default='', max_length=500, verbose_name='models:faq:verbose_name:external_url_text')),
            ],
        ),
    ]
