# Generated by Django 3.2.16 on 2023-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_nl',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='external_url_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='external_url_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='external_url_text_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='external_url_text_nl',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_nl',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='external_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='faq',
            name='external_url_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='faq',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
