# Generated by Django 4.2.3 on 2023-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_auto_20230623_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_slugs',
            field=models.TextField(default='', verbose_name='Line-separated list of related question slugs'),
        ),
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
