# Generated by Django 4.2.3 on 2023-08-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0026_rename_title_registration_registration_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='description',
            new_name='file_description',
        ),
    ]
