# Generated by Django 4.2.3 on 2023-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0028_faqlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faqlist',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
