# Generated by Django 4.2.3 on 2023-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0029_alter_faq_slug_alter_faqlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
