# Generated by Django 4.2.3 on 2023-09-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0030_alter_faq_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqlist',
            name='help_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_slugs',
            field=models.TextField(blank=True, default='', verbose_name='Line-separated list of related question slugs'),
        ),
    ]
