# Generated by Django 4.2.3 on 2023-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_faqlist_help_text_alter_faq_question_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqlist',
            name='show_help_text',
            field=models.BooleanField(default=True),
        ),
    ]
