# Generated by Django 4.2.6 on 2023-10-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0033_registration_submitter_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_title',
            field=models.CharField(help_text='models:registration_title_help_text', max_length=200, verbose_name='models:registrations:title_verbose_name'),
        ),
    ]
