# Generated by Django 4.2.6 on 2023-12-07 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0034_alter_registration_registration_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(help_text='models:response:approved_help_text', verbose_name='models:response:approved_verbose_name')),
                ('comments', models.CharField(blank=True, help_text='models:response:comments_help_text', max_length=1000, verbose_name='models:response:comments_verbose_name')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='responses_created', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration')),
            ],
        ),
    ]
